### PR TITLE
Swift 4.0 migration

### PR DESCRIPTION
**Pull request by VFUC**
Minor changes to make the project Swift 4.0 compatible, converted and built successfully using the Xcode 9 GM

Thanks for the project and cheers!

### CODE REVIEW

**Comment by VFUC** [comment]
Forgot to leave in a default parameter for the `show` method, patched back in with 88d1fee

**Comment by harlanhaskins** [comment]
Thanks for taking this on, @VFUC!

**Comment by ammadakhtar** [comment]
whats the fix i am getting the same error in swift4

**Comment by harlanhaskins** [comment]
What error are you getting?

**Comment by ammadakhtar** [comment]
@harlanhaskins   Class method 'topWindow()' is internal and cannot be referenced from a default argument value

**Comment by harlanhaskins** [comment]
Did you make sure to update your Podfile to use `0.8.0`, and update your pods?

**Comment by ammadakhtar** [comment]
the general guide of this repo didnt say to use version 0.8.0 @harlanhaskins

**Comment by harlanhaskins** [comment]
The guide doesn't really mention explicit versions at all. It just assumes you're gonna use the latest.

**Comment by ammadakhtar** [comment]
pod 'BRYXBanner', '~> 0.8.0' this is giving me an error while i try to install this ... whats the correct version? @harlanhaskins

**Comment by harlanhaskins** [comment]
What's the error you're getting? You need to run `pod repo update` before `pod install` as well.

**Comment by ammadakhtar** [comment]
Thanks it solved the issue @harlanhaskins

**Comment by harlanhaskins** [comment]
No problem! 😄

**Pull request merged**
