### PR TITLE
Add BannerManager

### PR DESCRIPTION
**Pull request by KyleMay**
Add a `BannerManager` class to keep track of banners so users can do things like clearing all visible banners, or only showing a banner if none are visible.

This addresses #82.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Thanks for your contribution! I think this is the wrong abstraction for this library.

For example, you can show persistent banners inside views that won’t conflict with top-level banners. I think hooking into the didSet on Banner.bannerState is the wrong place for something like that, and the fact that the Global BannerManager doesn’t ever remove a banner from its array means that they’ll stay alive forever 😕

Thanks again for tackling this, but unfortunately we don’t think this fits the purpose of the library.

**Comment by KyleMay** [comment]
Do you have an idea of a better implementation? I'm using this in my own app and I'd prefer to not have to use a fork and I'd be willing to give it another go in a different way.

**Comment by harlanhaskins** [comment]
I think you could use the BannerManager class as-is in your own app. What’s preventing that?

**Comment by KyleMay** [comment]
Nothing preventing it, I just thought it would be nice to have something built in to this library.

**Pull request closed without merging**
