### PR TITLE
Carthage support fix

### PR DESCRIPTION
**Pull request by makoni**

### CODE REVIEW

**Comment by harlanhaskins** [comment]
I thought I had fixed this. Carthage needs the example pods intact?

**Comment by makoni** [comment]
Yes. It worked before this commit: https://github.com/bryx-inc/BRYXBanner/commit/14690e5ae70fe642745c839f2bef202646432479

**Comment by harlanhaskins** [comment]
Then this is entirely my fault, and I apologize! 😕
Thanks for the investigation!

**Comment by makoni** [comment]
👍

**Comment by harlanhaskins** [comment]
I'll push up a new tag now. Check for 0.7.1.

**Comment by harlanhaskins** [comment]
Tag pushed.

**Comment by ikesyo** [comment]
@harlanhaskins 

> Carthage needs the example pods intact?

Carthage does not need a CocoaPods example project (off course!), but does need a Xcode project (`.xcodeproj`) which has a shared dynamic framework scheme (a framework target). If you'd like to remove the CocoaPods example project, you should make a new Xcode project that is dedicated for your framework target instead. See the related section of Carthage's README: https://github.com/Carthage/Carthage/tree/0.18#supporting-carthage-for-your-framework.

**Comment by makoni** [comment]
That would be much better than storing pods in repo :)

**Pull request merged**
