### PR TITLE
Adding the ability to change the height of the banner

### PR DESCRIPTION
**Pull request by drewg233**
It would be nice to allow the height of the banner to be changed instead of a hard coded height of 80.

### CODE REVIEW

**Review by harlanhaskins — CHANGES_REQUESTED** [review]
Can we change the property to `minimumHeight`? Otherwise LGTM. What's the use case for this?

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
Thanks! I'll push a release later this morning

**Comment by drewg233** [comment]
Thanks! Ya just adding more customization to the banner the better. 👍

**Comment by drewg233** [comment]
Did you happen to make a push yet?

**Pull request merged**
