### PR TITLE
Fixed Height Calculations

### PR DESCRIPTION
**Pull request by AnthonyMDev**
Fixed layout issues where height was not being calculated properly wh…en showing banner based on if it was being show in a view or the window and the appearance of the status bar.
- When shown in a view other than the `topWindow`, the banner's minimum height is 0, so that the banner sizes to it's content.
- When show in a view other than the `topWindow`, the height offset for the status bar no longer applies.
- When shown in the `topWindow` while the status bar is not shown (such as when in landscape orientation), the height offset for the status bar no longer applies.
- When shown in the `topWindow` while the status bar is not shown (such as when in landscape orientation), the minimum height for the status bar is set to a more appropriate height of `40`.
- All of the above changes update automatically upon orientation change.

### CODE REVIEW

**Comment by harlanhaskins** [comment]
You are the coolest person alive!

Before I merge this, could you post a couple screenshots of the behavior?

Thanks so much!!

**Comment by AnthonyMDev** [comment]
Ahaha thank you!

Sure I'd be happy to!
simulator screen shot nov 2 2015 5 17 22 pm
simulator screen shot nov 2 2015 5 17 59 pm
simulator screen shot nov 2 2015 5 18 20 pm

**Comment by harlanhaskins** [comment]
Amazing work. Thank you!

**Comment by AnthonyMDev** [comment]
Thank you for your quick response as always @harlanhaskins!

**Comment by AnthonyMDev** [comment]
Can I expect a new version of the Cocoapod to be pushed tomorrow so I can integrate these changes into my projects?

**Comment by harlanhaskins** [comment]
Done and pushed to pod-trunk!

**Comment by AnthonyMDev** [comment]
You rock!

**Pull request merged**
