### PR TITLE
Guard dismiss to only be called if banner is shown

### PR DESCRIPTION
**Pull request by relisiuol**
Fix issue #75

### CODE REVIEW

**Comment by nmanoogian** [comment]
Good find on this! One small style request: Instead of wrapping the logic with an if-statement, can you use a `guard bannerState == .showing else { return }` at the top?

**Comment by relisiuol** [comment]
Done

**Review by nmanoogian — APPROVED** [review]
Thanks!

**Comment by relisiuol** [comment]
Can you please increment pod version? I forgot that.

**Comment by billzeh** [comment]
yup, we'll take care of that

**Pull request merged**
