### PR TITLE
added showInView method (Issue 6) 

### PR DESCRIPTION
**Pull request by ashishawaghad**
https://github.com/bryx-inc/BRYXBanner/issues/6

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@difficultashish I left a few comments -- overall looks nice! :+1:

**Comment by ashishawaghad** [comment]
@harlanhaskins thanks :+1:
regarding making view non-optional, doesn't Banner.topWindow() return an optional?

**Comment by harlanhaskins** [comment]
So, through no fault of your own, this PR needs just a bit of work. I wrote the original implementation with an (admittedly wrongly) implicit understanding of the status bar.
So I wonder if it should be `func showInView(view: UIView, duration: NSTimeInterval? = nil, includesStatusBar: Bool = false)`

Actually, what if it was just `func show(view: UIView? = Banner.topWindow(), duration: NSTimeInterval? = nil, includesStatusBar: Bool = false)`?

We'll need to adjust the constraints for whether or not the status bar is there.

**Comment by harlanhaskins** [comment]
re: `Banner.topWindow()` returning an optional -- We pretty much want to fail badly if `topWindow()` is `nil`.
So I'd say make that a programmer error, and force-unwrap it.

**Comment by ashishawaghad** [comment]
Right. That's what I was going to say too. Anyway, I have now made the change you suggested and removed showInView. 

Can we do the statusBar change in a different pull request?

**Comment by harlanhaskins** [comment]
tumblr_mtyih4rek91s7mdj8o6_400

**Comment by ashishawaghad** [comment]
:)

**Pull request merged**
